channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::pyarrow
  - conda-forge::pip
  - bioconda::java-jdk=8
  - conda-forge::ipywidgets
  - conda-forge::nodejs
  - pip
  - pip:
    - plotly
    - py4j
    - bokeh
    - ipykernel
    - hail
    - pyspark==2.4.5
    - jupyter_server_proxy
